name: Build C++ Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use a Windows machine to compile the .exe

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Pull the code from your repository

    - name: Install MinGW Compiler
      run: |
        choco install mingw -y  # Install MinGW for compiling C++ on Windows
        set PATH=%PATH%;C:\tools\mingw64\bin

    - name: Build the Executable
      run: |
        g++ -o Arcieus.exe Arcieus.cpp  # Compile your C++ file into an .exe
        mkdir output
        move Arcieus.exe output/

    - name: Upload the Executable
      uses: actions/upload-artifact@v3  # Upload the .exe as an artifact
      with:
        name: Compiled-Arcieus
        path: output/Arcieus.exe
